parserOptions:
  ecmaVersion: 2021
  sourceType: "module"
env:
  es6: true
  browser: true
  cypress/globals: true
plugins:
  - prettier
  - cypress
  - svelte
extends:
  - plugin:svelte/recommended
  - plugin:prettier/recommended
overrides:
  - files:
      - "**/*.svelte"
    processor: "svelte/svelte"
rules:
  prettier/prettier: "error"
